language: python
python:
  - "3.6"
matrix:
  include:
  - name: "Validator tests"
    env: PYTEST_ARGS="test_helpers.py"
  - name: "EARTHENGINE-0.4"
    env: PYTEST_ARGS="--backend https://earthengine.openeo.org/v0.4 --api-version 0.4.2"
  - name: "VITO-0.3.1"
    env: PYTEST_ARGS="--backend http://openeo.vgt.vito.be/openeo/0.3.1"
  - name: "VITO-0.4.0"
    env: PYTEST_ARGS="--backend http://openeo.vgt.vito.be/openeo/0.4.0"
  - name: "EURAC-0.3.1"
    env: PYTEST_ARGS="--backend http://saocompute.eurac.edu/openEO_0_3_0/openeo --api-version 0.3.1"
  allow_failures:
  - env: PYTEST_ARGS="--backend https://earthengine.openeo.org/v0.4 --api-version 0.4.2"
  - env: PYTEST_ARGS="--backend http://openeo.vgt.vito.be/openeo/0.3.1"
  - env: PYTEST_ARGS="--backend http://openeo.vgt.vito.be/openeo/0.4.0"
  - env: PYTEST_ARGS="--backend http://saocompute.eurac.edu/openEO_0_3_0/openeo --api-version 0.3.1"
# command to install dependencies
before_install:
  - cd openeo_compliance_tests
install:
  - pip install -r requirements.txt
  - pip freeze
# command to run tests
script:
  - cd openeo_compliance_tests
  - pytest $PYTEST_ARGS