language: python
python:
  - "3.6"
matrix:
  include:
  - name: "EARTHENGINE"
    env: BACKEND=https://earthengine.openeo.org/v0.3
  - name: "VITO"
    env: BACKEND=http://openeo.vgt.vito.be/openeo
  - name: "EURAC"
    env: BACKEND=http://saocompute.eurac.edu/openEO_0_3_0/openeo
# command to install dependencies
before_install:
  - cd openeo_compliance_tests
install:
  - pip install -r requirements.txt
  - pip freeze
# command to run tests
script:
  - cd openeo_compliance_tests
  - pytest --backend $BACKEND