url="https://earthengine.openeo.org/v0.4"
openapi="openapi_0_4_1.json"
username="group1"
password="test123"
authurl="/credentials/basic"
endpoints= [ "/jobs", "/", "/collections" ]
#output="output.json"
