url="https://earthengine.openeo.org/v0.4"
openapi="openapi_0_4_1.json"
username="group10"
password="test123"
authurl="/credentials/basic"
endpoints= [ "/", "/output_formats", "/service_types", "/processes", "/collections", "/jobs", "/services", "/files/groupX", "/process_graphs/", "/me" ]
#output="output.json"
