#url="https://earthengine.openeo.org"
#backendversion = "1.0.0-rc.2"
#openapi="openapi_1_0_0rc2.yaml"
#openapi="openapi_1_0_0rc2.yaml"
#openapi="https://gist.githubusercontent.com/bgoesswe/8459bd57202e05a2951c130a2168ce3a/raw/8a43112d027df58f1e8fd3c069d975cee5087fd8/openeoapi-1.0.0rc2.json"
#openapi="https://gist.githubusercontent.com/bgoesswe/01111a3da271ba13cf70480e96574c9d/raw/cd6d87bc07684543ff9d549fa8d4039991784b2f/openeoapi_1_0_0rc2_2.json"
#username="group1"
#password="test123"
#authurl="/credentials/basic"
# output="test.json"

[variables]
  test = "/"
  test2 = "GET"
  test3 = "FIRMS2"
  gee_graph = "processgraph_endpoint_gee"

[endpoints]
  [endpoints.job_write]
  url = "/processes"
  request_type = "GET"
  group = "ADDITIONAL"
  # body = "examples/body/processgraph_endpoint_gee"

# [endpoints.job_read]
# url = "/jobs/ziDqkGf3whpkaQSC"
#  request_type = "GET"