url="https://earthengine.openeo.org/v0.3"
openapi="openapi_0_3_1.json"
username="group1"
password="test123"
authurl="/credentials/basic"
[endpoints]

  [endpoints.endpoint1]
  id = "endpoint1a"
  url = "/jobs"
  request_type = "GET"

  [endpoints.endpoint2]
  id = "endpoint2b"
  url = "/"
  request_type = "GET"

  [endpoints.endpoint3]
  id = "endpoint3c"
  url = "/collections"
  request_type = "GET"