config="examples/additional_config.toml"
#output="output.json"
 	
[endpoints]
  [endpoints.jobs]
 url = "/jobs"
  request_type = "POST"
  body = "examples/body/processgraph_endpoint_gee"
  timeout = 20
  optional = true
  group = "capabilities"

  [endpoints.jobs2]
  url = "/jobs/{job_id}"
  request_type = "GET"
  body = "examples/body/processgraph_endpoint_gee"
  optional = false
  group = "capabilities"

  [endpoints.job_write]
  url = "{test}"
  request_type = "GET"
  group = "ADDITIONAL"

  [endpoints.endpoint3]
  id = "output_formats"
  url = "/.well-known/openeo"
  request_type = "{test2}"

  [endpoints.endpoint4]
  id = "service_types"
  url = "/udf_runtimes"
  request_type = "GET"

  [endpoints.endpoint5]
  id = "{test2}"
  url = "/processes/{unknown_var}"
  request_type = "GET"

#  [endpoints.endpoint6]
#  id = "/services"
#  url = "/services"
#  request_type = "GET"

#  [endpoints.endpoint9]
#  id = "me"
#  url = "/me"
#  request_type = "GET"

  [endpoints.endpoint10]
  id = "endpoint3c"
  url = "/collections/{test3}"
  request_type = "GET"

  [endpoints.job_send]
  url = "/jobs"
  request_type = "POST"
  body = "examples/body/{gee_graph}"

  [endpoints.job_read]
  url = "/jobs/{job_id}"
  request_type = "GET"
#  body = "examples/body/processgraph_gee"

#  [endpoints.endpoint13]
#  id = "endpoint6"
#  url = "/process_graphs"
#  request_type = "POST"
#  body = "examples/body/processgraph_endpoint_gee"
