url="https://earthengine.openeo.org/v1.0"
openapi="openapi_1_0_0rc2.yaml"
#openapi="https://gist.githubusercontent.com/m-mohr/265efe594ee168e9ca122b6d47d9b8fd/raw/7feac299d188f8d79a286b4883946694e92c111d/openapi.json"
username="group1"
password="test123"
authurl="/credentials/basic"
#output="output.json"
[endpoints]
  [endpoints.endpoint1]
  url = "/jobs"
  request_type = "GET"
  optional = true
  group = "capabilities"

  [endpoints.endpoint2]
  url = "/"
  request_type = "GET"

  [endpoints.endpoint3]
  id = "output_formats"
  url = "/output_formats"
  request_type = "GET"

  [endpoints.endpoint11111]
  id = "output_formats2"
  url = "/asdasd"
  request_type = "GET"
  group = "capabilities"

  [endpoints.endpoint4]
  id = "service_types"
  url = "/udf_runtimes"
  request_type = "GET"

  [endpoints.endpoint5]
  id = "processes"
  url = "/processes"
  request_type = "GET"

  [endpoints.endpoint6]
  id = "/services"
  url = "/services"
  request_type = "GET"

  [endpoints.endpoint7]
  id = "/files/groupX"
  url = "/files/groupX"
  request_type = "GET"

  [endpoints.endpoint8]
  id = "process_graphs"
  url = "/process_graphs/"
  request_type = "GET"

  [endpoints.endpoint9]
  id = "me"
  url = "/me"
  request_type = "GET"

  [endpoints.endpoint10]
  id = "endpoint3c"
  url = "/collections"
  request_type = "GET"

  [endpoints.endpoint11]
  id = "endpoint4d"
  url = "/validation"
  request_type = "POST"
  body = "examples/body/processgraph_gee"

  [endpoints.endpoint12]
  id = "endpoint5"
  url = "/result"
  request_type = "POST"
  body = "examples/body/processgraph_gee"

  [endpoints.endpoint13]
  id = "endpoint6"
  url = "/process_graphs"
  request_type = "POST"
  body = "examples/body/processgraph_endpoint_gee"
